#!/usr/bin/env bash
# Purpose:
#   This script automates the process of renewing GPG keys, including extending their expiration,
#   generating new public keys and revocation certificates, and backing them up to 1Password.
#   It integrates with a `creds-op` script for secure handling of GPG credentials.
#
# Description:
#   The script performs the following steps:
#   1. Validates input parameters (key name and expiration in months).
#   2. Restores existing GPG keys (secret key, public key, revocation certificate) from 1Password
#      using the `creds-op` helper script.
#   3. Imports the restored keys into a temporary GnuPG home directory.
#   4. Extracts the GPG Key ID.
#   5. Establishes trust for the imported keys.
#   6. Backs up the existing public key and revocation certificate with a timestamp.
#   7. Extends the expiration date of the main key and sub-keys.
#   8. Exports the newly updated public key.
#   9. Publishes the updated public key to configured keyservers.
#   10. Generates a new revocation certificate.
#   11. Refreshes the user's main GnuPG keyring.
#   12. Backs up the new public key and revocation certificate to 1Password.
#   13. Cleans up temporary files and directories.
#
# Requirements:
#   Environment Variables:
#     - OP_GPG_VAULT      : Vault name in 1Password containing GPG credentials.
#     - OP_GPG_ITEM_UUID  : UUID of the 1Password item holding GPG keys and certificates.
#
#   Commands:
#     - gpg               : GnuPG command-line tool.
#     - op                : 1Password CLI tool.
#     - date              : For generating timestamps.
#     - mv                : For moving files.
#     - rm                : For removing files/directories.
#     - mkdir             : For creating directories.
#     - chmod             : For changing file permissions.
#     - awk               : For text processing.
#     - sed               : For text processing.
#     - dirname           : For getting directory name.
#
set -Eeuo pipefail
SCRIPT_DIR=$(cd `dirname "$BASH_SOURCE[@]"`; pwd)
CREDS_HOOK=$SCRIPT_DIR/creds-op
if [ ! -x "$CREDS_HOOK" ]; then
  echo "ERROR: $CREDS_HOOK does not exists or is not executable."
  exit 1
fi

function banner() {
  local message="$1"
  local width=80  # Adjust width as needed
  local padding=$(( (width - ${#message}) / 2 ))

  echo
  printf '=%.0s' $(seq 1 $width)
  printf '\n%*s\n' $((padding + ${#message})) "$message"
  printf '=%.0s' $(seq 1 $width)
  echo
}

# 1. Get Parameters and Validate
if [ $# -ne 2 ]; then
  echo "Usage: $0 <key_name> <expiration_in_months>"
  exit 1
fi

KEY_NAME="$1"
EXPIRATION_MONTHS="$2"

KEY_PASSWORD=$(creds-op password)
TIMESTAMP=$(date +%Y-%m-%d)
SK=$KEY_NAME.secretkey.pem
PK=$KEY_NAME.publickey.pem
RC=$KEY_NAME.revocationcert.pem
SK_BACKUP=$KEY_NAME-$TIMESTAMP.secretkey.pem
PK_BACKUP=$KEY_NAME-$TIMESTAMP.publickey.pem
RC_BACKUP=$KEY_NAME-$TIMESTAMP.revocationcert.pem


# Set GNUPG_HOME to the private directory
GNUPG_HOME="$PWD/.gpg"
export GNUPG_HOME

# Create GNUPG_HOME directory if it doesn't exist
if [ ! -d "$GNUPG_HOME" ]; then
  mkdir "$GNUPG_HOME"
  chmod 700 "$GNUPG_HOME"
fi

function gpg_edit_key (){
  KEY_ID="$1"
  gpg --homedir "$GNUPG_HOME" --pinentry-mode loopback --passphrase "$KEY_PASSWORD" --expert --command-fd 0 --batch --yes --edit-key "$KEY_ID"
}
function gpg_show_keys(){
  gpg --homedir "$GNUPG_HOME" -K --with-subkey-fingerprint --list-options=show-unusable-subkeys
}
function gpg_import_keys(){
  SK="$1"
  PK="$2"
  gpg --homedir "$GNUPG_HOME" --pinentry-mode loopback --passphrase "$KEY_PASSWORD" --expert --command-fd 0 --batch --import "$SK" "$PK"
}

banner "
  :::: Run Config ::::
  CREDS_HOOK          = $CREDS_HOOK
  TIMSTAMP            = $TIMESTAMP
  KEY_NAME            = $KEY_NAME
  EXPIRATION_MONTHS   = $EXPIRATION_MONTHS
  SK                  = $SK
  PK                  = $PK
  RC                  = $RC
  SK_BACKUP           = $SK_BACKUP
  PK_BACKUP           = $PK_BACKUP
  RC_BACKUP           = $RC_BACKUP
"

banner "Restore current keys ($SK, $PK, $RC)"
$CREDS_HOOK restore 

# Check if key files exist in current directory (KEY_DIR)
if [ ! -f "$SK" ] || \
   [ ! -f "$PK" ] || \
   [ ! -f "$RC" ]; then
  echo "Error: Key, certificate and revocation certificates are required. "
  exit 1
fi

banner "Importing Keys"

# 2. Load Keys from KEY_DIR
gpg_import_keys "$SK" "$PK"

# 3. Extract Key ID
KEY_ID=$(gpg --homedir "$GNUPG_HOME" --list-secret-keys --with-colons | awk -F ':' '$1 == "sec" {print $5}' | head -n 1)

if [ -z "$KEY_ID" ]; then
  echo "Error: Could not determine Key ID."
  exit 1
fi

banner "Trusting imported keys"

printf 'trust\n5\ny\nquit\n' | gpg_edit_key $KEY_ID
gpg_show_keys

echo "Imported Key ID: $KEY_ID"

# 3a. Remove secret key 
rm $SK

# 4. Backup Existing cert with Timestamp in KEY_DIR
banner "Backing Up Existing Keys"

mv "$PK" "$PK_BACKUP"

# 5. Extend the expiry
banner "Setting Key Expiration for Main Key"

echo -e "expire\n${EXPIRATION_MONTHS}m\nsave\nquit\n" | gpg_edit_key "$KEY_ID"

gpg_show_keys

banner "Setting Key Expiration for Sub-Keys"
  
echo -e "key 1\nkey 2\nexpire\ny\n${EXPIRATION_MONTHS}m\nsave\nquit\n" | gpg_edit_key "$KEY_ID"

gpg_show_keys

# 6. Extract New Certificate
banner "Extracting New Certificate"

gpg --homedir "$GNUPG_HOME" --armor --output "$KEY_NAME.publickey.pem" --export "$KEY_ID"
exit 1
banner "Publishing to Keyservers"
# # 7. Publish to Keyservers (Add more keyservers as needed)
for KID in $(gpg --homedir "$GNUPG_HOME" --armor --output "$KEY_NAME.publickey.pem" --export "$KEY_ID" | awk -F ':' '$1 == "fpr" {print $10}' )
do
  gpg --homedir "$GNUPG_HOME" --keyserver hkps://keys.openpgp.org --send-keys "$KID"
  gpg --homedir "$GNUPG_HOME" --keyserver hkp://keyserver.ubuntu.com --send-keys "$KID"
done


banner "Generating Revocation Certificate"
# 8. Generate Revocation Certificate (Non-interactively, directly in KEY_DIR)
mv "$RC" "$RC_BACKUP"
echo -e "y\n1\nDO NOT USE\n\ny\n" | gpg --homedir "$GNUPG_HOME" --command-fd=0 --output "$RC" --gen-revoke "$KEY_ID"


banner "Updating User's Keyring"

# 9. Update User's Main Keyring from Keyservers
gpg --refresh-keys

banner "Cleanup"
# 10. Backup keys and certs
creds-op backup

echo "Remove $PK, $RC, '$PK_BACKUP', and '$RC_BACKUP'"

# 11. Delete Temporary GNUPG_HOME
rm -rf "$GNUPG_HOME"

# (Optional) Display a success message
echo "GPG key and certificate management complete."
