#!/usr/bin/env bash
SCRIPT_ROOT=$( cd `dirname $0`; pwd)
PROJECT_ROOT=${PROJECT_ROOT:-$(cd $SCRIPT_ROOT/..; pwd)}
GNUPGHOME=$PROJECT_ROOT/.gpg

set -euo pipefail

PRIVATE_KEY=${1?"Missing private key path"}; shift
[[ !  -f $PRIVATE_KEY ]] && echo "$PRIVATE_KEY: Missing" && exit 1

echo "GNUPGHOME=$GNUPGHOME"

echo "Setup GNUPGHOME($GNUPGHOME)"
[[ -e $GNUPGHOME ]] &&  rm -rf $GNUPGHOME
mkdir -p $GNUPGHOME
chmod 700 $GNUPGHOME

KEY_ID=$(cat $PRIVATE_KEY | gpg --list-packets | grep keyid: | head -1 | awk {'print $2'})
[[ -z $KEY_ID ]] && echo "Key ID not found" && exit 1

export GNUPGHOME
export KEY_ID
export PRIVATE_KEY

echo "Receive Public Keys"
gpg --recv-keys $KEY_ID

echo "Listing Keys"
gpg --list-keys

echo "Import Private Key into GPG store"
gpg -a --import $PRIVATE_KEY

echo "Listing Secret Keys"
gpg --list-secret-keys


echo ===========================
echo EXECUTE
echo ===========================
echo export KEY_ID=$KEY_ID
echo export GNUPGHOME=$GNUPGHOME
echo ===========================
echo
echo ===========================
echo READ: $PROJECT_ROOT/RENEW.md or https://github.com/yogendra/gpg-renew/blob/main/RENEW.md
echo ===========================

